Blog app integration
rbreva/BlogApp pull request #9
Opened 2023-01-31 20:59 UTC by rbreva

### Blog app - integration
<hr>

:ballot_box_with_check: I have read this repository's contribution guidelines.
:ballot_box_with_check: My pull request has a descriptive title (not a vague title like Update index.MD)
:ballot_box_with_check: My pull request targets the main branch of this [project](https://github.com/rbreva/BlogApp).
:ballot_box_with_check: I added relevant documentation for all the files I changed

<hr>

-This PR solves the N + 1This PR solves the N + 1 problem and writes some integration tests
![Captura01](https://user-images.githubusercontent.com/54081966/215880747-9402f60a-ae86-4cad-a072-f463ee78432c.JPG)
![Captura02](https://user-images.githubusercontent.com/54081966/215880743-ed5a8633-6699-468f-ab1e-b25f499eee1f.JPG)

- Write user tests
- Write post tests

<hr>

👤 **Mauricio Mendoza**

- GitHub: [@rbreva](https://github.com/rbreva)
- Twitter: [@rbreva75](https://twitter.com/rbreva75)
- LinkedIn: [LinkedIn](https://www.linkedin.com/in/r-mauricio-mendoza-huerta/)

👤 **Didier Ganthier**

- GitHub: [@didierganthier](https://github.com/didierganthier)
- Twitter: [@didierganthier_](https://twitter.com/didierganthier_)
- LinkedIn: [Didier Peran Ganthier](https://linkedin.com/in/didierganthier)

<hr>

2023-01-31 21:53 UTC, Whoistolu requested changes
Hi @rbreva 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] Great job licensing this project but let's update the License year to 2023 as this is the year you built this project. Great job 👍🏽 

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 21:53 UTC, Whoistolu commented on spec/integration/user_spec.rb
> +  end
- [ ] [REQUIRED] Kindly note that for the featured tests for the User show page: You have missed the last 3 tests:
* Tests that assert you can see a button that lets me view all of a user's posts.
* Tests that redirects to the post's show page when you click on a user's post.
* Tests that redirect to the user's post's index page when you click on a **see all posts**.

Kindly add these tests before asking for another review.

2023-01-31 21:53 UTC, Whoistolu commented on spec/integration/post_spec.rb
> +  end
- [ ] [REQUIRED] Please take a look at the featured tests for `User` **post index page**: You have missed out on this test:
- Tests that assert you can see a section for pagination if there are more posts than fit on the view.

Kindly fix this before asking for another review.

2023-02-01 03:59 UTC, FrederickMih approved these changes
## Hi 🙋 @rbreva  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights <img src="https://media.giphy.com/media/Zcm5DaspYzhTxstkF4/giphy.gif" width="30" height="30"/>

- PR is professional ✔️ 
- All tests scenarios covered ✔️ 
- Linter checks passed ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 03:59 UTC, FrederickMih commented on README.md
>  ## 🔭 Future Features <a name="future-features"></a>
- As pointed out by the previous reviewer, your license file still contains obsolete information as you can see in the screenshot below:

![Capture](https://user-images.githubusercontent.com/63087491/215939745-bc07192b-e033-4e72-be52-0009092d8c5e.PNG)

- You really need to update the required information(date and name)

2023-02-01 04:44 UTC, merged